Moving the publish condition to the jenkins file

diff --git a/bin/publish b/bin/publish
--- a/bin/publish
+++ b/bin/publish
@@ -5,7 +5,7 @@
 REDHAT_IMAGE='scan.connect.redhat.com/ospid-1c46a2de-1d88-40e6-a433-7114ad0099cb/conjur-openshift-authenticator-client'
 
 readonly REGISTRY="cyberark"
-readonly VERSION="$(short_version_tag)"
+readonly VERSION="${TAG_NAME//"v"}"
 
 # we changed the name to `conjur-authn-k8s-client`. Leaving `conjur-kubernetes-authenticator`
 # for backwards-compatibility.
@@ -19,34 +19,29 @@ readonly TAGS=(
   "latest"
 )
 
-# The push should run only on fixed versions, identified by the existence of the TAG_NAME environment variable
-# which happens automatically in tag-triggered builds. 
-# push VERSION and latest releases and x and x.y releases
-if [[ ! -z "${TAG_NAME:-}" ]]; then
-  echo "Revision $git_description matches version $VERSION exactly"
+echo "This script should not run in a tag-triggered build. controlled by the JenkinsFile"
 
-  echo "Pushing to Dockerhub..."
-  source_image=conjur-authn-k8s-client:dev
-  for destination_image_name in "${DESTINATION_IMAGES[@]}"; do
-    for tag in "${TAGS[@]}" $(gen_versions "$VERSION"); do
-      echo "Tagging and pushing $REGISTRY/$destination_image_name:$tag"
-      docker tag $source_image "$REGISTRY/$destination_image_name:$tag"
-      docker push "$REGISTRY/$destination_image_name:$tag"
-    done
+echo "Pushing to Dockerhub..."
+source_image=conjur-authn-k8s-client:dev
+for destination_image_name in "${DESTINATION_IMAGES[@]}"; do
+  for tag in "${TAGS[@]}" $(gen_versions "$VERSION"); do
+    echo "Tagging and pushing $REGISTRY/$destination_image_name:$tag"
+    docker tag $source_image "$REGISTRY/$destination_image_name:$tag"
+    docker push "$REGISTRY/$destination_image_name:$tag"
   done
+done
 
-  echo "Pushing to RedHat container registry..."
-  source_redhat_image=conjur-authn-k8s-client-redhat:dev
-  docker tag $source_redhat_image "$REDHAT_IMAGE:$VERSION"
+echo "Pushing to RedHat container registry..."
+source_redhat_image=conjur-authn-k8s-client-redhat:dev
+docker tag $source_redhat_image "$REDHAT_IMAGE:$VERSION"
 
-  if docker login scan.connect.redhat.com -u unused -p "$REDHAT_API_KEY"; then
-    # you can't push the same tag twice to redhat registry, so ignore errors
-    if ! docker push "${REDHAT_IMAGE}:${VERSION}"; then
-      echo 'RedHat push FAILED! (maybe the image was pushed already?)'
-      exit 0
-    fi
-  else
-    echo 'Failed to log in to scan.connect.redhat.com'
-    exit 1
+if docker login scan.connect.redhat.com -u unused -p "$REDHAT_API_KEY"; then
+  # you can't push the same tag twice to redhat registry, so ignore errors
+  if ! docker push "${REDHAT_IMAGE}:${VERSION}"; then
+    echo 'RedHat push FAILED! (maybe the image was pushed already?)'
+    exit 0
   fi
+else
+  echo 'Failed to log in to scan.connect.redhat.com'
+  exit 1
 fi
