Added automated release process to project pipeline
- Downgraded go.mod to 1.16 to match the Dockerfile version

- Added workaround for git CVE-2022-24765 in Dockerfile.helm-unit-test

- Project pipeline moved to azure-linux executor allowing public IP
access for workflow tests.

- Reconfigured bin/publish to perform releases and promotions
of contianer images based on optional flag parameters.

- Added additional functions in bin/build_utils for the automated releases.

- Maintained legacy bin/build_utils functions that are currently no longer in
use, but might provide useful in the future.

- Added go get @latest for conjur-opentelemetry-tracer upstream dependency.

- Moved temp directory creation to /bin/test-workflow/start. The temp directory
must be created by the jenkins user to prevent permission issues within
the directory. This also removes the possibility of a race condition when parallel
test stages are running and allows for developers to skip tests
during the development process.

- Added stage to push images internally to registry.tld. This allows for promoting
these images at a later time.

diff --git a/bin/publish b/bin/publish
--- a/bin/publish
+++ b/bin/publish
@@ -1,63 +1,147 @@
 #!/bin/bash -e
 
+# The following is used to:
+# Publish images on pre-release and tag as edge
+# Promote pre-releases to releases and tag as latest
+
 . bin/build_utils
 
-REDHAT_IMAGE='scan.connect.redhat.com/ospid-1c46a2de-1d88-40e6-a433-7114ad0099cb/conjur-openshift-authenticator-client'
+function print_help() {
+  echo "Build Usage: $0 --internal"
+  echo "Release Usage: $0 --edge"
+  echo "Promote Usage: $0 --promote --source <VERSION> --target <VERSION>"
+  echo " --internal: publish images to registry.tld"
+  echo " --edge: publish docker images to docker hub"
+  echo " --source <VERSION>: specify version number of local image"
+  echo " --target <VERSION>: specify version number of remote image"
+}
 
-readonly REGISTRY="cyberark"
-
-if [[ $1 = "--edge" ]]; then
-    tag=edge
-    push_conjur-k8s-cluster-test
-    exit 0
+# Fail if no arguments are given.
+if [[ $# -lt 1 ]]; then
+  print_help
+  exit 1
 fi
 
-# We take the version from the TAG_NAME variable - removing the "v" prefix
-readonly VERSION="${TAG_NAME//"v"}"
+PUBLISH_INTERNAL=false
+PUBLISH_EDGE=false
+PROMOTE=false
+
+while [[ $# -gt 0 ]]; do
+  case "$1" in
+  --internal)
+    PUBLISH_INTERNAL=true
+    ;;
+  --edge)
+    PUBLISH_EDGE=true
+    ;;
+  --promote)
+    PROMOTE=true
+    ;;
+  --source)
+    SOURCE_ARG="$2"
+    shift
+    ;;
+  --target)
+    TARGET_ARG="$2"
+    shift
+    ;;
+  --help)
+    print_help
+    exit 1
+    ;;
+  *)
+    echo "Unknown option: ${1}"
+    print_help
+    exit 1
+    ;;
+  esac
+  shift
+done
+
+REDHAT_REMOTE_IMAGE='scan.connect.redhat.com/ospid-1c46a2de-1d88-40e6-a433-7114ad0099cb/conjur-openshift-authenticator-client'
+readonly REGISTRY="cyberark"
+readonly REDHAT_LOCAL_IMAGE="conjur-authn-k8s-client-redhat"
 
 # we changed the name to `conjur-authn-k8s-client`. Leaving `conjur-kubernetes-authenticator`
 # for backwards-compatibility.
-readonly DESTINATION_IMAGES=(
+readonly DOCKER_IMAGES=(
   "conjur-kubernetes-authenticator"
   "conjur-authn-k8s-client"
 )
 
-readonly TAGS=(
-  "$VERSION"
-  "latest"
-)
+  # Version derived from CHANGLEOG and automated release library
+  VERSION=$(<VERSION)
+  readonly VERSION
 
-if [[ -z "${TAG_NAME:-}" ]]; then
-  echo "This script should only run in a tag-triggered build controlled by the JenkinsFile"
-  exit 1
+if [[ ${PUBLISH_INTERNAL} = true ]]; then
+  echo "Publishing built images internally to registry.tld."
+  SOURCE_TAG=dev
+  REMOTE_TAG=$VERSION
+
+  tag_and_push "conjur-authn-k8s-client:${SOURCE_TAG}" "registry.tld/conjur-authn-k8s-client:${REMOTE_TAG}"
+
+  tag_and_push ${REDHAT_LOCAL_IMAGE}:${SOURCE_TAG} "registry.tld/${REDHAT_LOCAL_IMAGE}:${REMOTE_TAG}"
 fi
 
-echo "Pushing to Dockerhub..."
-source_image=conjur-authn-k8s-client:dev
-for destination_image_name in "${DESTINATION_IMAGES[@]}"; do
-  for tag in "${TAGS[@]}" $(gen_versions "$VERSION"); do
-    echo "Tagging and pushing $REGISTRY/$destination_image_name:$tag"
-    docker tag $source_image "$REGISTRY/$destination_image_name:$tag"
-    docker push "$REGISTRY/$destination_image_name:$tag"
+if [[ ${PUBLISH_EDGE} = true ]]; then
+  echo "Performing docker edge release."
+  SOURCE_TAG=dev
+  REMOTE_TAG=edge
+  readonly TAGS=(
+    "$REMOTE_TAG"
+    "$VERSION"
+  )
+
+  push_conjur-k8s-cluster-test
+
+  for image in "${DOCKER_IMAGES[@]}"; do
+    echo "Tagging and pushing ${image} to docker hub."
+    for tag in "${TAGS[@]}"; do
+      tag_and_push "conjur-authn-k8s-client:${SOURCE_TAG}" "${REGISTRY}/${image}:${tag}"
+    done
   done
-done
-
-echo "Pushing to RedHat container registry..."
-source_redhat_image=conjur-authn-k8s-client-redhat:dev
-docker tag $source_redhat_image "$REDHAT_IMAGE:$VERSION"
-
-if docker login scan.connect.redhat.com -u unused -p "$REDHAT_API_KEY"; then
-  # you can't push the same tag twice to redhat registry, so ignore errors
-  if ! docker push "${REDHAT_IMAGE}:${VERSION}"; then
-    echo 'RedHat push FAILED! (maybe the image was pushed already?)'
-    exit 0
-  fi
-else
-  echo 'Failed to log in to scan.connect.redhat.com'
-  exit 1
 fi
 
-for tag in "${TAGS[@]}" $(gen_versions "$VERSION"); do
-    push_conjur-k8s-cluster-test
-done
+if [[ ${PROMOTE} = true ]]; then
+  if [[ -z ${SOURCE_ARG:-} || -z ${TARGET_ARG:-} ]]; then
+  echo "When promoting, --source and --target flags are required."
+    print_help
+    exit 1
+  fi
 
+  # Update vars to utilize build_utils
+  SOURCE_TAG=$SOURCE_ARG
+  REMOTE_TAG=$TARGET_ARG
+
+  # Promotes image based on flag values provided
+  echo "Promoting image from ${SOURCE_TAG} to ${REMOTE_TAG}"
+  readonly TAGS=(
+    "$REMOTE_TAG"
+    "latest"
+  )
+
+  for image in "${DOCKER_IMAGES[@]}"; do
+    echo "Tagging and pushing ${image} to docker hub."
+    for tag in "${TAGS[@]}" $(gen_versions "${REMOTE_TAG}"); do
+      tag_and_push "conjur-authn-k8s-client:${SOURCE_TAG}" "${REGISTRY}/${image}:${tag}"
+    done
+  done
+
+  echo "Pushing to RedHat container registry..."
+  docker tag "${REDHAT_LOCAL_IMAGE}:${SOURCE_TAG}" "${REDHAT_REMOTE_IMAGE}:${REMOTE_TAG}"
+
+  if docker login scan.connect.redhat.com -u unused -p "${REDHAT_API_KEY}"; then
+    # you can't push the same tag twice to redhat registry, so ignore errors
+    if ! docker push "${REDHAT_REMOTE_IMAGE}:${REMOTE_TAG}"; then
+      echo 'RedHat push FAILED! (maybe the image was pushed already?)'
+      exit 0
+    fi
+  else
+    echo 'Failed to log in to scan.connect.redhat.com'
+    exit 1
+  fi
+
+  for REMOTE_TAG in "${TAGS[@]}" $(gen_versions "${REMOTE_TAG}"); do
+    push_conjur-k8s-cluster-test
+  done
+fi
