Implement changes to workflow scripts

diff --git a/bin/test-workflow/start b/bin/test-workflow/start
--- a/bin/test-workflow/start
+++ b/bin/test-workflow/start
@@ -1,26 +1,18 @@
-#!/usr/bin/env bash
-set -xeuo pipefail
+#!/bin/bash
 
-. set_env_vars.sh
-. utils.sh
-init_bash_lib
+set -eo pipefail
 
-./0_prep_check_dependencies.sh
+cd "$(dirname "$0")" || ( echo "cannot cd into dir" && exit 1 )
 
-./stop
+. ./0_prep_conjur_in_kind.sh
 
-./1_prep_platform_login.sh
+. ./1_prep_check_dependencies.sh
 
-if [[ "${CONFIGURE_CONJUR_MASTER}" == "true" || "${CONJUR_OSS_HELM_INSTALLED}" == "true" ]]; then
-  # Only automatically run these scripts for dev/demo envs deploying a master
-  # cluster directly to k8s/oc
-  ./2_admin_load_conjur_policies.sh
-  ./3_admin_init_conjur_cert_authority.sh
-fi
+./2_admin_load_conjur_policies.sh
+./3_admin_init_conjur_cert_authority.sh
 
-./4_app_create_namespace.sh
-./5_app_store_conjur_cert.sh
+./4_kubernetes_cluster_prep.sh
+./5_app_namespace_prep.sh
 ./6_app_build_and_push_containers.sh
 ./7_app_deploy.sh
 ./8_app_verify_authentication.sh
-
